input_directory: "/home/dittohead/inbox"
processing_directory: "/home/dittohead/processing"
done_directory: "/home/dittohead/done"
study_directory: "/home/dittohead/study-fake"
study_dittohead_raw_folder_name: "raw-data"
log_directory: "/home/dittohead/log"
