"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['dittohead.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'arch': 'i386', 
    'iconfile': 'dittohead.icns',
    'plist': {
        'CFBundleName': 'Dittohead',
        'CFBundleShortVersionString':'1.0.0', # must be in X.X.X format
        'CFBundleVersion': '1.0.0',
        'CFBundleIdentifier':'edu.wisc.dittohead', 
        'NSHumanReadableCopyright': 'None',
        'CFBundleDevelopmentRegion': 'English',
    },
    'dist_dir': 'osx_dist',
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={
        'py2app': OPTIONS,
        "build": {
            'build_base': 'osx_build',
        }
    },
    setup_requires=['py2app'],
)
